name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          make init

      - name: Run tests
        run: |
          make test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ GITHUB_ACTOR }}
          password: ${{ secrets.TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ GITHUB_REPOSITORY }}:latest

      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v3
      #   with:
      #     app-name: 'health-calculator-app'
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     images: 'ghcr.io/${{ GITHUB_REPOSITORY }}:latest'
